### ISSUE TITLE
Parser error on correct multiple binary conditions

### ISSUE THREAD

**Issue by quantumkoen** [QE-Lab/libqasm#88]
The following code (from line 13 in code example 3 in the cqasm 1.0 paper):

```
version 1.0 

qubits 5

c-x b[0],b[1],q[4]
```

Results in a syntax error:

```

  =================================================================================================== 
        _______                                                                                       
       /  ___   \   _  __      ____   ____   __  ___  __  __   __    ___  ______  ____    ___         
      /  /   /  |  | |/_/     / __/  /  _/  /  |/  / / / / /  / /   / _ |/_  __/ / __ \  / _ \        
     /  /___/  /  _>  <      _\ \   _/ /   / /|_/ / / /_/ /  / /__ / __ | / /   / /_/ / / , _/        
     \______/\__\ /_/|_|    /___/  /___/  /_/  /_/  \____/  /____//_/ |_|/_/    \____/ /_/|_|         
                                                                                                      
     version 0.2 beta - QuTech - 2018 - report bugs and suggestions to: nader.khammassi@gmail.com
  =================================================================================================== 

[+] loading circuit from '../../code.qasm' ...
error while parsing file ../../code.qasm: 
syntax error, unexpected BITHEAD, expecting NAME or QBITHEAD | Token 299 on Line: 5
```

**Comment by kel85uk** [comment]
AFAIK, this was already discussed with Nader and the example is not supposed to work that way. I suppose it wasn't updated? It breaks the syntax. One must make a numeric list, e.g.
`c-x b[0, 1, 4], q[4]`

**Comment by quantumkoen** [comment]
@Nader-Khammassi can you confirm the above? Can the spec paper be updated?

**Comment by kel85uk** [comment]
Check the qasm test file example3.qasm for the updated example?

**Comment by quantumkoen** [comment]
@kel85uk so it turns out users of qx-simulator don't check the libqasm examples to find out what valid syntax is, but rather refer to the cqasm paper (odd, I know :) and assume that what is described there is valid syntax. That is how this bug report came about, someone was looking at the paper and trying things described there, and then got syntax errors.

**Comment by kel85uk** [comment]
It's fine either way. We need to make things consistent though. Perhaps we should just relax the grammar to accept such changes. Need further discussion on this.

**Comment by jvanstraten** [comment]
The documentation for cQASM, now [here](https://libqasm.readthedocs.io/en/latest/) instead of in paper form, [documents this behavior](https://libqasm.readthedocs.io/en/latest/cq1-instructions.html#conditional-instructions) of the language. There are more inconsistencies between the paper and the parser implementation, by the way; the test code of the new API includes all the [examples](https://github.com/QE-Lab/libqasm/tree/193651b51873380fcd6e6bf3abfbe6fb8280b395/src/cqasm/tests/parsing/paper) in the paper with the behavior as it was prior to the new API (successful parse or parse failure) as well as fixed versions of the examples that failed to parse. Unfortunately the language cannot easily be changed because it could break existing cQASM files, and the paper cannot be changed because it's already on arXiv and I don't have its source files anyway.

I considered `c-c-x b[0], b[1], q[4]` for cQASM at one point for clearer syntax than what's there right now. This would be backward compatible and easy to do even in the type-system-based grammar. However, the expressions that have since been added provide a much more flexible way of specifying multiple conditions going forward. It'd look like this:

```
c-x b[0] && b[1], q[4]
```

or, using the new conditional syntax,

```
cond(b[0] && b[1]) x q[4]
```

Until targets support that however, `c-x b[0,1], q[4]` would be the way to go, awkward as it may be.
